<div class="viewProfile">
	<h2>${model.title!}</h2>
	<table width="100%" cellspacing="1" cellpadding="1" border="0">
		<tbody>
			<tr>
				<td>Benutzername</td>
				<td>${model.member.username!}</td>
			</tr>
			<tr>
				<td>Vorname</td>
				<td>${model.member.prename!}</td>
			</tr>
			<tr>
				<td>Nachname</td>
				<td>${model.member.lastname!}</td>
			</tr>
			<tr>
				<td>Mail</td>
				<td>${model.member.mail!}</td>
			</tr>
			<tr>
				<td>Telefonnummer</td>
				<td>${model.member.phoneNumber!}</td>
			</tr>
			<tr>
				<td>Mobiltelefonnummer</td>
				<td>${model.member.mobilePhoneNumber!}</td>
			</tr>
			<tr>
				<td>Adresse</td>
				<td>${model.member.address!}</td>
			</tr>
			<tr>
				<td>Postleitzahl</td>
				<td>${model.member.postalCode!}</td>
			</tr>
			<tr>
				<td>Ort</td
				><td>${model.member.city!}</td>
			</tr>
		</tbody>
	</table>
</div>